---
# An Ansible Playbook to backup the Mikrotik device's configuration to both script and backup file
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik Change Device Password
  hosts: mikrotik
  connection: paramiko
  gather_facts: no
  vars_prompt:
   vpn_range_var: "Введите пул адресов l2tp"
  tasks:
   - name: Add l2tp_pool
     raw: /ip pool add name=l2tp_pool ranges={{vpn_range_var}}

   - name: Add PPP profile
     raw: /ppp profile add local-address={{vpn_address_var}} name=l2tp_profile remote-address=l2tp_pool

   - name: Add l2tp server
     raw: /interface l2tp-server server set default-profile=l2tp_profile enabled=yes ipsec-secret={{ipsecpsk_var}} use-ipsec=yes authentication=mschap2
   
   - name: Add firewall rules ipsec-esp
     raw: /ip firewall filter add action=accept chain=input protocol=ipsec-esp comment="L2TP Server" disabled=no place-before=1
   - name: Add firewall rules udp
     raw: /ip firewall filter add action=accept chain=input dst-port=1701,500,4500 protocol=udp disabled=no place-before=1
