---
# An Ansible Playbook to backup the Mikrotik device's configuration to both script and backup file
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik Change iptables
  hosts: mikrotik
  connection: paramiko
  gather_facts: no
  tasks:
   - name: Adding ITBP Address List
     raw: /ip firewall address-list add list=ITBP address={{address_var}}
   
   - name: Adding INPUT rule for access from ITBP adress list
     raw: /ip firewall filter add action=accept src-address-list=ITBP chain=INPUT