---
# An Ansible Playbook to change the Mikrotik device's password and add user
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik Change Device Password
  hosts: "{{hosts_var}}"
  connection: paramiko
  gather_facts: no
  tasks:
   - name: Add user
     raw: /user add name={{username_var}} password={{password_var}} group=full disabled=no comment="ITBP admin"
     tags: adduser
     
   - name: Changing password
     raw: /user set {{username_var}} password={{password_var}}
     tags: setpass
     
   - name: User delete
     raw: /user remove {{remname_var}}
     tags: remuser
