---
# An Ansible Playbook to backup the Mikrotik device's configuration to both script and backup file
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik ADD VPN Users
  hosts: vpn
  connection: paramiko
  gather_facts: no
  tasks:
   - name: Add {{vpn_user1_var}}
     raw: /ppp secret add name={{vpn_user1_var}} password={{vpn_pass1_var}} profile=l2tp_profile service=l2tp
     tags: 1users

   - name: Add {{vpn_user1_var}}
     raw: /ppp secret add name={{vpn_user1_var}} password={{vpn_pass1_var}} profile=l2tp_profile service=l2tp
     tags: 2users

   - name: Add {{vpn_user2_var}}
     raw: /ppp secret add name={{vpn_user2_var}} password={{vpn_pass2_var}} profile=l2tp_profile service=l2tp
     tags: 2users

   - name: Add {{vpn_user1_var}}
     raw: /ppp secret add name={{vpn_user1_var}} password={{vpn_pass1_var}} profile=l2tp_profile service=l2tp
     tags: 3users

   - name: Add {{vpn_user2_var}}
     raw: /ppp secret add name={{vpn_user2_var}} password={{vpn_pass2_var}} profile=l2tp_profile service=l2tp
     tags: 3users

   - name: Add {{vpn_user3_var}}
     raw: /ppp secret add name={{vpn_user3_var}} password={{vpn_pass3_var}} profile=l2tp_profile service=l2tp
     tags: 3users

   - name: Add {{vpn_user1_var}}
     raw: /ppp secret add name={{vpn_user1_var}} password={{vpn_pass1_var}} profile=l2tp_profile service=l2tp
     tags: 4users

   - name: Add {{vpn_user2_var}}
     raw: /ppp secret add name={{vpn_user2_var}} password={{vpn_pass2_var}} profile=l2tp_profile service=l2tp
     tags: 4users

   - name: Add {{vpn_user3_var}}
     raw: /ppp secret add name={{vpn_user3_var}} password={{vpn_pass3_var}} profile=l2tp_profile service=l2tp
     tags: 4users

   - name: Add {{vpn_user4_var}}
     raw: /ppp secret add name={{vpn_user4_var}} password={{vpn_pass4_var}} profile=l2tp_profile service=l2tp
     tags: 4users

   - name: Add {{vpn_user1_var}}
     raw: /ppp secret add name={{vpn_user1_var}} password={{vpn_pass1_var}} profile=l2tp_profile service=l2tp
     tags: 5users

   - name: Add {{vpn_user2_var}}
     raw: /ppp secret add name={{vpn_user2_var}} password={{vpn_pass2_var}} profile=l2tp_profile service=l2tp
     tags: 5users

   - name: Add {{vpn_user3_var}}
     raw: /ppp secret add name={{vpn_user3_var}} password={{vpn_pass3_var}} profile=l2tp_profile service=l2tp
     tags: 5users

   - name: Add {{vpn_user4_var}}
     raw: /ppp secret add name={{vpn_user4_var}} password={{vpn_pass4_var}} profile=l2tp_profile service=l2tp
     tags: 5users

   - name: Add {{vpn_user5_var}}
     raw: /ppp secret add name={{vpn_user5_var}} password={{vpn_pass5_var}} profile=l2tp_profile service=l2tp
     tags: 5users
