---
# An Ansible Playbook to backup the Mikrotik device's configuration to both script and backup file
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik Change Device Password
  hosts: mikrotik
  connection: paramiko
  gather_facts: no
  tasks:
   - name: Add user
     raw: /user 
     add name={{username_var}} password={{password_var}} group=full disabled=no comment="ITBP admin"
     set name={{username_var}} password={{password_var}} numbers={{numbers_var}} group=full disabled=no comment="ITBP admin"
     remove {{remname_var}}

